// Language Level Converter line number map: dj*->java. Entries: 16
//     1->4         2->5         3->6         4->7         5->8         6->9         7->10        8->11   
//     9->12       10->13       11->14       12->15       13->16       14->17       15->18       16->49   
import javax.swing.*;
import javax.swing.ImageIcon;

public class DialogBoxImages {
  public static void main(final String[] args) {
      
    final ImageIcon picture = new ImageIcon("my logo.png");
    
    
    
    
    JOptionPane.showMessageDialog(null,"This is my logo!",
                                  "Adding Images Tutorial",JOptionPane.INFORMATION_MESSAGE, picture);
  }

  /** This method is automatically generated by the Language Level Converter. */
  public DialogBoxImages() {
    super();
  }

  /** This method is automatically generated by the Language Level Converter. */
  public java.lang.String toString() {
    return getClass().getName() + "(" + 
        ")";
  }

  /** This method is automatically generated by the Language Level Converter. */
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    else if ((o == null) || (! o.getClass().equals(getClass()))) {
      return false;
    }
    else {
      DialogBoxImages cast = ((DialogBoxImages) o);
      return true;
    }
  }

  /** This method is automatically generated by the Language Level Converter. */
  public int hashCode() {
    return getClass().hashCode();
  }
}
    
